export const STRINGS = {
  roman_urdu: {
    nav: { home:'Ghar', chat:'Chat', disease:'Bimari', weather:'Mausam', mandi:'Mandi', farm:'Zameen', services:'Khadmaat', season:'Calendar' },
    langPicker: { title:'Zaban Chunein', sub:'App kis zaban mein chalani hai?', continueBtn:'Aage Barein →' },
    home: {
      tagline: "Pakistan ke kisanon ka AI saathi",
      sectionLabel: "KYA KARNA CHAHEIN?",
      loginBtn: "Login",
      infoSetup: "Apna profile set karein",
      infoSetupSub: "Meri Zameen mein jaa kar apni fasal aur sheher save karein",
      todayLabel: "📍 Aaj ka haal — {loc}",
      features: [
        { title: "Kisan Chat", sub: "AI se sawaal poochein" },
        { title: "Bimari Scanner", sub: "Fasal ki tasveer lein" },
        { title: "Mausam", sub: "5-din ka haal" },
        { title: "Mandi Bhav", sub: "Sabse acha bhaav" },
        { title: "Meri Zameen", sub: "Farm update karein" },
        { title: "AI Calendar", sub: "Fasal ka plan" }
      ]
    },
    chat: {
      title:'Kisan AI', subtitle:'● Online · Roman Urdu',
      initialMsg:'Salam! Main Kisan AI hoon. Apna masla batayein.',
      placeholder:'Apna masla likhen...', typing:'AI soch raha hai...',
      errorMsg:'Server se connection nahi mili. Baad mein try karein.',
    },
    disease: {
      title:'Fasal ki Bimari', subtitle:'Tasveer se AI bimari pehchanein',
      uploadTitle:'Fasal ki tasveer lein',
      uploadSub:'Bimari wali jagah saaf aur qareeb se dikhni chahiye',
      cameraBtn:'📷  Camera', galleryBtn:'🖼  Gallery', analyzeBtn:'🌾  Bimari Pehchano',
      tipsTitle:'📌  Behtar natijon ke liye',
      tips:['Subah ki roshni mein tasveer lein','Bimari wale patte ke qareeb jayein','Camera steady rakhein'],
      resetBtn:'← Nai Tasveer Lein',
      expertLabel:'👨‍⚕️  Pehle Expert Se Milein',
      expertSub:'Dawai kharidne se pehle expert se milein — bilkul muft',
      callExpert:'📞  Call Expert', treatmentTitle:'💊  Mustanad Ilaj',
      safetyText:'⚠️  Dawai ke saath mask aur dastane zaroor pehnen',
      confidence:'% yakeen', analysisError:'Analysis fail hui. Dobara try karein.',
      cropLabel:'Fasal ka naam', acreLabel:'Kanal / Acre'
    },
    weather: {
      title: "Mausam",
      city: "Aap ka sheher",
      forecastLabel: "5-Din Ka Andaza",
      advisoryLabel: "Ziraati Salah",
      urgentTitle: "Fori Ittela!",
      riskLabel: "Is hafte ka khatra",
      riskHigh: "Zyada",
      riskMedium: "Darmiyana",
      riskLow: "Kam",
      harvestLabel: "Behtar katayi",
      actionTitle: "Aaj kya karein",
      loadingText: "Mausam ki maloomat la rahe hain...",
      errorText: "Location nahi mili. Meri Zameen mein apna sheher save karein.",
      days:['Aaj','Kal','Budh','Jum','Shan'],
    },
    mandi: {
      title: "Mandi Bhav",
      subtitle: "Aaj ke live prices — Pakistan",
      bestLabel: "SABSE ACHA BHAAV",
      aiTitle: "AI ki Salah",
      allLabel: "TAMAM MANDIYAAN",
      unit: "/40kg",
      dist: "km door",
      sellNow: "Abhi bechein",
      wait3: "3-5 din ruko",
      wait1: "1 hafte ruko",
      trending: "Market trend",
      rising: "↑ Barh raha hai",
      falling: "↓ Gir raha hai",
      stable: "→ Stable hai",
      govtPrice: "Govt support price",
      noData: "Data load nahi hua. Dobara try karein.",
      netLabel: "Net",
      transportLabel: "transport",
      crops: ["Gehun", "Chawal", "Ganna", "Kapas", "Makai", "Pyaz", "Aloo"],
      defaultAdvice:'Agla hafte demand barhnay ki ummeed hai. 5–7 din ruk ke farokhst karein.',
    },
    farm: {
      title: "Meri Zameen",
      subtitle: "Apna profile update karein",
      verified: "✓ Verified Kisan",
      langLabel: "🌐 Zaban ka Intikhab",
      langHint: "Zaban badalne se poori app mein text badal jayega",
      cropLabel: "🌾 Fasal ka Intikhab",
      infoLabel: "📋 Farm ki Maloomat",
      acreLabel: "Rukba (Acre)",
      cityLabel: "Sheher ya Ilaaqa",
      saveBtn: "💾 Profile Save Karein",
      savedBtn: "✅ Save ho gaya!",
      saving: "Save ho raha hai...",
      locating: "Location dhundh rahe hain...",
      locationFound: "Location milgayi",
      mustCity: "Sheher ka naam likhein",
      mustCrop: "Fasal chunein",
      successText: "Aap ka profile save ho gaya. Ab chat mein aap ki fasal aur location automatically use hogi.",
      crops: ["Gehun", "Chawal", "Ganna", "Kapas", "Makkai", "Doosra"]
    },
    services: {
      title: "Khadmaat",
      subtitle: "Aalaat, mazdoor, zakhira",
      selectPrompt: "Ooper se koi khadmat chunein aur qareeby faraham kar deikhein",
      services: [
        { label: "Combine Harvester", value: "harvester", emoji: "🚜" },
        { label: "Tractor", value: "tractor", emoji: "🚛" },
        { label: "Spray Drone", value: "drone", emoji: "🚁" },
        { label: "Mazdoor", value: "labor", emoji: "👷" },
        { label: "Storage", value: "storage", emoji: "🏭" },
        { label: "Transport", value: "transport", emoji: "🚌" }
      ]
    },
    auth: {
      loginTitle:'Apne Account mein Darakhwast', loginSub:'Login karein aur AI ki madad lein',
      emailLabel:'📧  Email', passLabel:'🔒  Password',
      forgotPass:'Password bhool gaye?', loginBtn:'Login Karein →',
      orText:'Ya', googleBtn:'Google se Login Karein',
      signupPrompt:'Naya account? ', signupLink:'Abhi Banayen',
      signupTitle:'Kisan AI mein Khush Aamdeed!', signupSub:'Apni maloomat bhar ke shuru karein',
      nameLabel:'👤  Apna Naam', phoneLabel:'📱  Phone Number', confirmLabel:'🔒  Password Dobara',
      termsText:'Main Kisan AI ki ', termsLink:'Shartein wa Zaroorat', termsEnd:' se raazi hoon',
      signupBtn:'Account Banayen →', googleSignupBtn:'Google se Sign Up Karein',
      loginPrompt:'Pehle se account hai? ', loginLink:'Login Karein',
      strengthWeak:'Kamzor', strengthFair:'Theek', strengthStrong:'Mazboot',
    },
    forgotPassword:{
      title:'Password Bhool Gaye?', sub:'Apna email darain, hum reset link bhejein ge',
      emailLabel:'📧  Email', sendBtn:'Reset Link Bhejen →',
      backToLogin:'← Login par wapas jayein',
      successTitle:'Email Bhej Di Gayi!', successSub:'Apna inbox check karein aur password reset karein.',
      emailRequired:'Email darain', emailInvalid:'Email sahi nahi hai',
    },
    errors: {
      emailRequired:'Email darain', emailInvalid:'Email sahi nahi hai',
      passRequired:'Password darain', passShort:'Password kam az kam 6 huroof ka ho',
      confirmRequired:'Password dobara darain', confirmMismatch:'Dono password aik jaise honay chahiye',
      nameRequired:'Naam darain (kam az kam 2 huroof)',
      phoneRequired:'Phone number darain', phoneInvalid:'Pakistani number (03xxxxxxxxx) darain',
      termsRequired:'Shartein manzoor karein',
    },
  },

  urdu: {
    nav: { home:'گھر', chat:'چیٹ', disease:'بیماری', weather:'موسم', mandi:'منڈی', farm:'زمین', services:'خدمات', season:'کیلنڈر' },
    langPicker: { title:'زبان چنیں', sub:'ایپ کس زبان میں چلانی ہے؟', continueBtn:'آگے بڑھیں →' },
    home: {
      tagline: "پاکستان کے کسانوں کا AI ساتھی",
      sectionLabel: "کیا کرنا چاہیں؟",
      loginBtn: "لاگ ان",
      infoSetup: "اپنا پروفائل سیٹ کریں",
      infoSetupSub: "میری زمین میں جا کر اپنی فصل اور شہر محفوظ کریں",
      todayLabel: "📍 آج کا حال — {loc}",
      features: [
        { title: "کسان چیٹ", sub: "AI سے سوال پوچھیں" },
        { title: "بیماری سکینر", sub: "فصل کی تصویر لیں" },
        { title: "موسم", sub: "5 دن کا حال" },
        { title: "منڈی بھاؤ", sub: "سب سے اچھا بھاؤ" },
        { title: "میری زمین", sub: "فارم اپڈیٹ کریں" },
        { title: "AI کیلنڈر", sub: "فصل کا پلان" }
      ]
    },
    chat:{
      title:'کسان AI', subtitle:'● آن لائن · اردو',
      initialMsg:'السلام علیکم! میں کسان AI ہوں۔ اپنا مسئلہ بتائیں۔',
      placeholder:'اپنا سوال لکھیں...', typing:'AI سوچ رہا ہے...',
      errorMsg:'سرور سے کنکشن نہیں ملا۔ بعد میں کوشش کریں۔',
    },
    disease:{
      title:'فصل کی بیماری', subtitle:'تصویر سے AI بیماری پہچانے',
      uploadTitle:'فصل کی تصویر لیں', uploadSub:'بیماری والی جگہ صاف اور قریب سے دکھنی چاہیے',
      cameraBtn:'📷  کیمرہ', galleryBtn:'🖼  گیلری', analyzeBtn:'🌾  بیماری پہچانو',
      tipsTitle:'📌  بہتر نتائج کے لیے',
      tips:['صبح کی روشنی میں تصویر لیں','بیمار پتے کے قریب جائیں','کیمرہ مستحکم رکھیں'],
      resetBtn:'← نئی تصویر لیں', expertLabel:'👨‍⚕️  پہلے ماہر سے ملیں',
      expertSub:'دوائی خریدنے سے پہلے ماہر سے ملیں — بالکل مفت',
      callExpert:'📞  ماہر کو کال کریں', treatmentTitle:'💊  معتمد علاج',
      safetyText:'⚠️  دوائی کے ساتھ ماسک اور دستانے ضرور پہنیں',
      confidence:'% یقین', analysisError:'تجزیہ ناکام ہوا۔ دوبارہ کوشش کریں۔',
      cropLabel:'فصل کا نام', acreLabel:'کنال / ایکڑ'
    },
    weather: {
      title: "موسم",
      city: "آپ کا شہر",
      forecastLabel: "5 دن کا اندازہ",
      advisoryLabel: "زراعتی مشورہ",
      urgentTitle: "فوری اطلاع!",
      riskLabel: "اس ہفتے کا خطرہ",
      riskHigh: "زیادہ",
      riskMedium: "درمیانہ",
      riskLow: "کم",
      harvestLabel: "بہتر کٹائی",
      actionTitle: "آج کیا کریں",
      loadingText: "موسم کی معلومات لا رہے ہیں...",
      errorText: "لوکیشن نہیں ملی۔ میری زمین میں اپنا شہر محفوظ کریں۔",
      days:['آج','کل','بدھ','جمعہ','ہفتہ'],
    },
    mandi: {
      title: "منڈی بھاؤ",
      subtitle: "آج کی لائیو قیمتیں — پاکستان",
      bestLabel: "سب سے اچھا بھاؤ",
      aiTitle: "AI کی صلاح",
      allLabel: "تمام منڈیاں",
      unit: "/40کلو",
      dist: "کلومیٹر دور",
      sellNow: "ابھی بیچیں",
      wait3: "3-5 دن رکیں",
      wait1: "1 ہفتہ رکیں",
      trending: "مارکیٹ ٹرینڈ",
      rising: "↑ بڑھ رہا ہے",
      falling: "↓ گر رہا ہے",
      stable: "→ مستحکم ہے",
      govtPrice: "حکومتی سپورٹ قیمت",
      noData: "ڈیٹا لوڈ نہیں ہوا۔ دوبارہ کوشش کریں۔",
      netLabel: "خالص",
      transportLabel: "ٹرانسپورٹ",
      crops: ["گندم", "چاول", "گنا", "کپاس", "مکئی", "پیاز", "آلو"],
      defaultAdvice:'اگلے ہفتے مانگ بڑھنے کی امید ہے۔ 5-7 دن رک کر فروخت کریں۔',
    },
    farm: {
      title: "میری زمین",
      subtitle: "اپنا پروفائل اپڈیٹ کریں",
      verified: "✓ تصدیق شدہ کسان",
      langLabel: "🌐 زبان کا انتخاب",
      langHint: "زبان بدلنے سے پوری ایپ میں متن بدل جائے گا",
      cropLabel: "🌾 فصل کا انتخاب",
      infoLabel: "📋 فارم کی معلومات",
      acreLabel: "رقبہ (ایکڑ)",
      cityLabel: "شہر یا علاقہ",
      saveBtn: "💾 پروفائل محفوظ کریں",
      savedBtn: "✅ محفوظ ہو گیا!",
      saving: "محفوظ ہو رہا ہے...",
      locating: "لوکیشن ڈھونڈ رہے ہیں...",
      locationFound: "لوکیشن مل گئی",
      mustCity: "شہر کا نام لکھیں",
      mustCrop: "فصل چنیں",
      successText: "آپ کا پروفائل محفوظ ہو گیا۔ اب چیٹ میں آپ کی فصل اور لوکیشن خودکار استعمال ہوگی۔",
      crops: ["گندم", "چاول", "گنا", "کپاس", "مکئی", "دوسرا"]
    },
    services: {
      title: "خدمات",
      subtitle: "آلات، مزدور، ذخیرہ",
      selectPrompt: "اوپر سے کوئی خدمت چنیں اور قریبی فراہم کار دیکھیں",
      services: [
        { label: "کمبائن ہارویسٹر", value: "harvester", emoji: "🚜" },
        { label: "ٹریکٹر", value: "tractor", emoji: "🚛" },
        { label: "سپرے ڈرون", value: "drone", emoji: "🚁" },
        { label: "مزدور", value: "labor", emoji: "👷" },
        { label: "ذخیرہ", value: "storage", emoji: "🏭" },
        { label: "ٹرانسپورٹ", value: "transport", emoji: "🚌" }
      ]
    },
    auth:{
      loginTitle:'اپنے اکاؤنٹ میں داخل ہوں', loginSub:'لاگ ان کریں اور AI کی مدد لیں',
      emailLabel:'📧  ای میل', passLabel:'🔒  پاس ورڈ',
      forgotPass:'پاس ورڈ بھول گئے؟', loginBtn:'لاگ ان کریں →',
      orText:'یا', googleBtn:'گوگل سے لاگ ان کریں',
      signupPrompt:'نیا اکاؤنٹ؟ ', signupLink:'ابھی بنائیں',
      signupTitle:'کسان AI میں خوش آمدید!', signupSub:'اپنی معلومات بھر کر شروع کریں',
      nameLabel:'👤  اپنا نام', phoneLabel:'📱  فون نمبر', confirmLabel:'🔒  پاس ورڈ دوبارہ',
      termsText:'میں کسان AI کی ', termsLink:'شرائط و ضروریات', termsEnd:' سے راضی ہوں',
      signupBtn:'اکاؤنٹ بنائیں →', googleSignupBtn:'گوگل سے سائن اپ کریں',
      loginPrompt:'پہلے سے اکاؤنٹ ہے؟ ', loginLink:'لاگ ان کریں',
      strengthWeak:'کمزور', strengthFair:'ٹھیک', strengthStrong:'مضبوط',
    },
    forgotPassword:{
      title:'پاس ورڈ بھول گئے؟', sub:'اپنا ای میل درج کریں، ہم ری سیٹ لنک بھیجیں گے',
      emailLabel:'📧  ای میل', sendBtn:'ری سیٹ لنک بھیجیں →',
      backToLogin:'← لاگ ان پر واپس جائیں',
      successTitle:'ای میل بھیج دی گئی!', successSub:'اپنا ان باکس چیک کریں اور پاس ورڈ ری سیٹ کریں۔',
      emailRequired:'ای میل درج کریں', emailInvalid:'ای میل درست نہیں',
    },
    errors:{
      emailRequired:'ای میل درج کریں', emailInvalid:'ای میل درست نہیں',
      passRequired:'پاس ورڈ درج کریں', passShort:'پاس ورڈ کم از کم 6 حروف کا ہو',
      confirmRequired:'پاس ورڈ دوبارہ درج کریں', confirmMismatch:'دونوں پاس ورڈ ایک جیسے ہونے چاہئیں',
      nameRequired:'نام درج کریں (کم از کم 2 حروف)',
      phoneRequired:'فون نمبر درج کریں', phoneInvalid:'پاکستانی نمبر (03xxxxxxxxx) درج کریں',
      termsRequired:'شرائط منظور کریں',
    },
  },

  english: {
    nav: { home:'Home', chat:'Chat', disease:'Disease', weather:'Weather', mandi:'Mandi', farm:'Farm', services:'Services', season:'Calendar' },
    langPicker: { title:'Select Language', sub:'Choose your preferred language', continueBtn:'Continue →' },
    home: {
      tagline: "Pakistan's AI companion for farmers",
      sectionLabel: "WHAT WOULD YOU LIKE TO DO?",
      loginBtn: "Login",
      infoSetup: "Set up your profile",
      infoSetupSub: "Go to My Farm to save your crop and city",
      todayLabel: "📍 Today's update — {loc}",
      features: [
        { title: "Kisan Chat", sub: "Ask AI anything" },
        { title: "Disease Scanner", sub: "Scan your crop" },
        { title: "Weather", sub: "5-day forecast" },
        { title: "Mandi Prices", sub: "Best market price" },
        { title: "My Farm", sub: "Update farm profile" },
        { title: "AI Calendar", sub: "Crop planner" }
      ]
    },
    chat:{
      title:'Kisan AI', subtitle:'● Online · English',
      initialMsg:'Hello! I am Kisan AI. Please describe your problem.',
      placeholder:'Type your question...', typing:'AI is thinking...',
      errorMsg:'Could not connect to server. Please try again later.',
    },
    disease:{
      title:'Crop Disease', subtitle:'AI identifies disease from your photo',
      uploadTitle:'Take a crop photo', uploadSub:'The diseased area should be clear and close-up',
      cameraBtn:'📷  Camera', galleryBtn:'🖼  Gallery', analyzeBtn:'🌾  Identify Disease',
      tipsTitle:'📌  For best results',
      tips:['Photograph in morning light','Get close to the diseased leaf','Keep camera steady'],
      resetBtn:'← Take New Photo', expertLabel:'👨‍⚕️  Consult Expert First',
      expertSub:'See an expert before buying medicine — completely free',
      callExpert:'📞  Call Expert', treatmentTitle:'💊  Recommended Treatment',
      safetyText:'⚠️  Always wear mask and gloves when applying medicine',
      confidence:'% confidence', analysisError:'Analysis failed. Please try again.',
      cropLabel:'Crop Name', acreLabel:'Kanal / Acre'
    },
    weather: {
      title: "Weather",
      city: "Your location",
      forecastLabel: "5-Day Forecast",
      advisoryLabel: "Farming Advisory",
      urgentTitle: "Urgent Alert!",
      riskLabel: "This week's risk",
      riskHigh: "High",
      riskMedium: "Medium",
      riskLow: "Low",
      harvestLabel: "Best harvest window",
      actionTitle: "What to do today",
      loadingText: "Loading weather data...",
      errorText: "Location not found. Save your city in My Farm screen.",
      days:['Today','Tomorrow','Wed','Fri','Sat'],
    },
    mandi: {
      title: "Mandi Prices",
      subtitle: "Today's live prices — Pakistan",
      bestLabel: "BEST PRICE",
      aiTitle: "AI Advice",
      allLabel: "ALL MARKETS",
      unit: "/40kg",
      dist: "km away",
      sellNow: "Sell now",
      wait3: "Wait 3-5 days",
      wait1: "Wait 1 week",
      trending: "Market trend",
      rising: "↑ Rising",
      falling: "↓ Falling",
      stable: "→ Stable",
      govtPrice: "Govt support price",
      noData: "Data not loaded. Please try again.",
      netLabel: "Net",
      transportLabel: "transport cost",
      crops: ["Wheat", "Rice", "Sugarcane", "Cotton", "Maize", "Onion", "Potato"],
      defaultAdvice:'Demand is expected to rise next week. Consider waiting 5–7 days before selling.',
    },
    farm: {
      title: "My Farm",
      subtitle: "Update your farm profile",
      verified: "✓ Verified Farmer",
      langLabel: "🌐 Language Selection",
      langHint: "Changing language will update all text in the app",
      cropLabel: "🌾 Select Your Crop",
      infoLabel: "📋 Farm Information",
      acreLabel: "Area (Acres)",
      cityLabel: "City or Region",
      saveBtn: "💾 Save Profile",
      savedBtn: "✅ Saved!",
      saving: "Saving...",
      locating: "Finding location...",
      locationFound: "Location found",
      mustCity: "Please enter your city",
      mustCrop: "Please select a crop",
      successText: "Profile saved. Your crop and location will now be used automatically in chat.",
      crops: ["Wheat", "Rice", "Sugarcane", "Cotton", "Maize", "Other"]
    },
    services: {
      title: "Services",
      subtitle: "Equipment, labor, storage",
      selectPrompt: "Select a service above to find nearby providers",
      services: [
        { label: "Combine Harvester", value: "harvester", emoji: "🚜" },
        { label: "Tractor", value: "tractor", emoji: "🚛" },
        { label: "Spray Drone", value: "drone", emoji: "🚁" },
        { label: "Labor", value: "labor", emoji: "👷" },
        { label: "Storage", value: "storage", emoji: "🏭" },
        { label: "Transport", value: "transport", emoji: "🚌" }
      ]
    },
    auth:{
      loginTitle:'Sign In to Your Account', loginSub:'Login and get AI assistance',
      emailLabel:'📧  Email', passLabel:'🔒  Password',
      forgotPass:'Forgot password?', loginBtn:'Login →',
      orText:'Or', googleBtn:'Continue with Google',
      signupPrompt:"Don't have an account? ", signupLink:'Sign Up',
      signupTitle:'Welcome to Kisan AI!', signupSub:'Fill in your details to get started',
      nameLabel:'👤  Full Name', phoneLabel:'📱  Phone Number', confirmLabel:'🔒  Confirm Password',
      termsText:'I agree to Kisan AI ', termsLink:'Terms & Conditions', termsEnd:'',
      signupBtn:'Create Account →', googleSignupBtn:'Sign Up with Google',
      loginPrompt:'Already have an account? ', loginLink:'Login',
      strengthWeak:'Weak', strengthFair:'Fair', strengthStrong:'Strong',
    },
    forgotPassword:{
      title:'Forgot Password?', sub:'Enter your email and we will send you a reset link',
      emailLabel:'📧  Email', sendBtn:'Send Reset Link →',
      backToLogin:'← Back to Login',
      successTitle:'Email Sent!', successSub:'Check your inbox and reset your password.',
      emailRequired:'Email is required', emailInvalid:'Invalid email address',
    },
    errors:{
      emailRequired:'Email is required', emailInvalid:'Invalid email address',
      passRequired:'Password is required', passShort:'Password must be at least 6 characters',
      confirmRequired:'Please confirm your password', confirmMismatch:'Passwords do not match',
      nameRequired:'Name must be at least 2 characters',
      phoneRequired:'Phone number is required', phoneInvalid:'Enter a valid Pakistani number (03xxxxxxxxx)',
      termsRequired:'Please accept the terms',
    },
  },
};
